#!/bin/bash

# Quick manual password setup
echo "🔑 Manual Database Password Setup"
echo "=================================="
echo ""
echo "You need to get your database password from Supabase:"
echo ""
echo "1. Go to: https://lzkhjmtfvksxobxdjytb.supabase.co"
echo "2. Click 'Settings' (gear icon) in left sidebar"
echo "3. Click 'Database'"
echo "4. Scroll to 'Connection string' section"
echo "5. Find the 'URI' field - it shows your password"
echo ""
echo "The URI looks like:"
echo "postgresql://postgres:PASSWORD_HERE@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
echo ""
echo "6. Copy the password part (between 'postgres:' and '@aws-1...')"
echo "7. Replace [YOUR-PASSWORD] in your .env file"
echo ""
echo "Example:"
echo "DATABASE_URL=\"postgresql://postgres:COPIED_PASSWORD_HERE@aws-1-ap-south-1.pooler.supabase.com:5432/postgres\""
echo ""
echo "Then run: ./quick-setup.sh"